import "./globals.css";
import Link from "@/node_modules/next/link";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="p-5">
        <main>
          <nav className="flex gap-2 text-blue-500 text-xl mb-2">
            <Link className="underline" href="/">
              Home
            </Link>
            <Link className="underline" href="/notes">
              Notes
            </Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
